sonar.projectKey=nodejs-eks
sonar.projectName=Node.js EKS DevOps Project
sonar.projectVersion=1.0

sonar.sources=nodejs-eks-app/src
sonar.tests=tests

sonar.exclusions=**/node_modules/**,**/coverage/**,**/dist/**

sonar.sourceEncoding=UTF-8
