sonar.projectKey=nodejs-eks
sonar.projectName=Node.js EKS Application

sonar.sources=nodejs-eks-app/src
sonar.tests=nodejs-eks-app/tests

sonar.exclusions=nodejs-eks-app/node_modules/**,nodejs-eks-app/coverage/**,nodejs-eks-app/dist/**

sonar.sourceEncoding=UTF-8